# Generated by Django 3.2.8 on 2021-10-15 11:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20211015_1544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('client1', 'client2')},
        ),
    ]
